name: riverpod_mutations
description: A stop-gap measure for riverpod mutations, until its supported
version: 1.0.0
repository: https://github.com/TekExplorer/riverpod_mutations

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  riverpod: ^2.2.0
  riverpod_generator: ^1.2.0
  test: ^1.21.0
  
dependencies:
  meta: ^1.9.0
  riverpod_annotation: ^1.2.1
  stack_trace: ^1.11.0
